### ISSUE TITLE
Doesn't work for pull_requests

### ISSUE THREAD

**Issue by rlorenzo** [CareMessagePlatform/check-if-merged#22]
If I set the on condition to be for pull_request instead of push the action doesn't run.

```
name: Check if branch is merged to staging
on:
  pull_request:
    branches-ignore:
      - 'master'
      - 'staging'
jobs:
  check-if-merged:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: CareMessagePlatform/check-if-merged@v1
```

Is it possible to make this action work just when someone makes a pull request? I don't want the check to fail for branches that are works in progress and aren't ready to be merged to staging yet.

BTW, the link on the Marketplace is broken: https://github.com/marketplace/actions/check-if-merged

**Comment by rlorenzo** [comment]
Okay, I had to remove branches-ignore for it to work

```
name: Check if branch is merged to staging
on: pull_request
jobs:
  check-if-merged:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: CareMessagePlatform/check-if-merged@v1
```

Closing.
